# Generated by Django 6.0.1 on 2026-02-05 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(blank=True, choices=[('UPPER', 'UPPER'), ('LOWER', 'LOWER'), ('PULL', 'PULL'), ('PUSH', 'PUSH'), ('FULLBODY', 'FULLBODY')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('variation', models.CharField(choices=[('DUMBBELL', 'DUMBBELL'), ('BARBELL', 'BARBELL'), ('MACHINE', 'MACHINE'), ('BODYWEIGHT', 'BODYWEIGHT'), ('OTHER', 'OTHER')], max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='training.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='training.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='training.sessionexercise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session_exercise', 'order'), name='uniq_exerciseset_order_per_session_exercise')],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionexercise',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_sessionexercise_order_per_session'),
        ),
    ]
