# Generated by Django 6.0.1 on 2026-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_sessionexercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(blank=True, choices=[('UPPER', 'UPPER'), ('LOWER', 'LOWER'), ('PULL', 'PULL'), ('PUSH', 'PUSH'), ('FULLBODY', 'FULLBODY')], default='', max_length=20),
        ),
    ]
